[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
staking_contract = "7Uq92WE6XL6KJ8dhuE22KgcKEk5wrqMAEr62RjUeMb8J"


[programs.localnet]
staking_contract = "BTU1s63ZvrPDqLeawE4BdoFWq4nnJ8aWz6PcHcnUgT2N"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
